//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long RegionId { get; set; }
        public string Phone { get; set; }
        public long ManagerId { get; set; }
        public string Description { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Region Region { get; set; }
    }
}
