//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long RegionId { get; set; }
        public string Phone { get; set; }
        public long ManagerId { get; set; }
        public string Description { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Region Region { get; set; }
    }
}
