//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour_booking
    {
        public long Booking_id { get; set; }
        public long Tour_id { get; set; }
        public decimal Price { get; set; }
        public long People_count { get; set; }
        public long Id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
