//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourSell
    {
        public long Id { get; set; }
        public long TourId { get; set; }
        public long SellId { get; set; }
        public decimal Price { get; set; }
        public long PeopleCount { get; set; }
    
        public virtual Sell Sell { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
