//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public long Id { get; set; }
        public long Hotel_id { get; set; }
        public System.DateTime Arrival_date { get; set; }
        public System.DateTime Departure_date { get; set; }
        public long Feeding_id { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
    
        public virtual Feeding Feeding { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
