//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Tour_booking = new HashSet<Tour_booking>();
        }
    
        public long Id { get; set; }
        public long Hotel_id { get; set; }
        public System.DateTime Arrival_date { get; set; }
        public System.DateTime Departure_date { get; set; }
        public long Feeding_id { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
    
        public virtual Feeding Feeding { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour_booking> Tour_booking { get; set; }
    }
}
